
# Site settings
# 站点名字，也就是html的title 会显示在浏览器标签上。
title: 马学俊
#name: 
# 站点副标题，会显示在首页上，可以不填。
subtitle: 
email: 
# 站点描述，可以不填
description: 

# Sidebar settings
#sidebar: true # 是否开启侧边栏.

# SNS settings 展示你的其他社交平台
#RSS: false
#github_username:    



# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true







# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag




